<a href="https://colab.research.google.com/github/dinsor17/KKU_Data_mining/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

##numpy array

In [2]:
np1 = np.array([[1,3,5],[2,4,6]])
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [5]:
np2 = np.array([[1,2],[3,5],[2,0],[4,5]])
np2

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [6]:
np2.T

array([[1, 3, 2, 4],
       [2, 5, 0, 5]])

In [7]:
np2[0,:] #แถวกับหลัก

array([1, 2])

##HW 6 สร้าง Distance metrix (Mahattan and Euclidean) ของ np2 
โดยสร้าง function สำหรับคำนวณ Mahattan Distance และ Euclidean Distance
 
 
 det Euclidean(data1,data2): 
   #process
   
   return dist 


In [25]:
def Manhattan(data1,data2) : 
      distx = data1[0]-data2[0]
      return distx

In [26]:
def Manhattan(data1,data2) : 
      distX = abs(data[0]-data2[0])
      distY = abs(data[1]-data2[1])
      return distX+distY

In [27]:
Manhattan(np2[0,:],np2[1,:])

NameError: ignored

In [30]:
dist_mat = mat = np.zeros((4,4))
dist_mat 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
for i in range(4) :
     for j in range(4) :
          dist_mat[i,j] = Manhattan(np2[],np2[])

dist_mat         

SyntaxError: ignored